import { TVShowDetail } from "@/src/types/TVShowDetail";
import { TVShowCreditsResponse } from "@/src/types/TVShowCredits";
import { TVShowListResponse } from "@/src/types/TVShowList";

export const mockTVShowDetailsData: TVShowDetail = {
  id: 1,
  name: "Test TV Show",
  overview: "Test overview",
  backdrop_path: "/backdrop.jpg",
  poster_path: "/poster.jpg",
  first_air_date: "2020-01-01",
  last_air_date: "2023-01-01",
  vote_average: 8.5,
  episode_run_time: [30, 45],
  number_of_episodes: 24,
  number_of_seasons: 2,
  status: "Returning Series",
  genres: [
    { id: 18, name: "Drama" },
    { id: 10765, name: "Sci-Fi & Fantasy" },
  ],
  created_by: [
    {
      id: 12345,
      name: "Creator Name",
      credit_id: "credit123",
      gender: 0,
      profile_path: "/creator.jpg",
    },
  ],
  networks: [
    {
      id: 201,
      name: "Test Network",
      logo_path: "/network.jpg",
      origin_country: "US",
    },
  ],
  seasons: [
    {
      id: 101,
      name: "Season 1",
      air_date: "2020-01-01",
      episode_count: 10,
      overview: "First season",
      poster_path: "/season1.jpg",
      season_number: 1,
    },
    {
      id: 102,
      name: "Season 2",
      air_date: "2022-01-01",
      episode_count: 14,
      overview: "Second season",
      poster_path: "/season2.jpg",
      season_number: 2,
    },
  ],
  production_companies: [
    {
      id: 101,
      name: "Test Studio",
      logo_path: "/studio.jpg",
      origin_country: "US",
    },
  ],
  homepage: "https://example.com/testshow",
  in_production: true,
  languages: ["en"],
  origin_country: ["US"],
  original_language: "en",
  original_name: "Test TV Show",
  popularity: 100,
  tagline: "A test tagline",
  type: "Scripted",
  vote_count: 1000,
};

export const mockTVShowCreditsData: TVShowCreditsResponse = {
  id: 1,
  cast: [
    {
      id: 1,
      name: "Actor 1",
      character: "Character 1",
      profile_path: "/actor1.jpg",
      credit_id: "credit1",
      order: 0,
      adult: false,
      gender: 2,
      known_for_department: "Acting",
      original_name: "Actor 1",
      popularity: 10,
    },
    {
      id: 2,
      name: "Actor 2",
      character: "Character 2",
      profile_path: "/actor2.jpg",
      credit_id: "credit2",
      order: 1,
      adult: false,
      gender: 1,
      known_for_department: "Acting",
      original_name: "Actor 2",
      popularity: 8,
    },
  ],
  crew: [
    {
      id: 3,
      name: "Director Name",
      job: "Director",
      department: "Directing",
      profile_path: "/director.jpg",
      credit_id: "credit3",
      adult: false,
      gender: 2,
      known_for_department: "Directing",
      original_name: "Director Name",
      popularity: 5,
    },
    {
      id: 4,
      name: "Writer Name",
      job: "Writer",
      department: "Writing",
      profile_path: "/writer.jpg",
      credit_id: "credit4",
      adult: false,
      gender: 1,
      known_for_department: "Writing",
      original_name: "Writer Name",
      popularity: 4,
    },
    {
      id: 5,
      name: "Producer Name",
      job: "Executive Producer",
      department: "Production",
      profile_path: "/producer.jpg",
      credit_id: "credit5",
      adult: false,
      gender: 1,
      known_for_department: "Production",
      original_name: "Producer Name",
      popularity: 6,
    },
  ],
};

export const mockSimilarTVShowsData: TVShowListResponse = {
  page: 1,
  results: [
    {
      id: 2,
      name: "Similar TV Show 1",
      poster_path: "/similar1.jpg",
      backdrop_path: "/backdrop1.jpg",
      vote_average: 7.5,
      first_air_date: "2019-05-15",
      overview: "This is a similar TV show",
      original_name: "Similar TV Show 1",
      origin_country: ["US"],
      genre_ids: [18, 10765],
      original_language: "en",
      popularity: 85,
      vote_count: 800,
    },
    {
      id: 3,
      name: "Similar TV Show 2",
      poster_path: "/similar2.jpg",
      backdrop_path: "/backdrop2.jpg",
      vote_average: 8.0,
      first_air_date: "2020-03-20",
      overview: "Another similar TV show",
      original_name: "Similar TV Show 2",
      origin_country: ["US"],
      genre_ids: [18, 10759],
      original_language: "en",
      popularity: 75,
      vote_count: 700,
    },
  ],
  total_pages: 1,
  total_results: 2,
};

export const mockTVShowError = new Error("Failed to load TV show");
